export {
  openai,
  detectAudioFormat,
  convertToWav,
  ensureCompatibleFormat,
  whisperVerboseTranscribe,
  type AudioFormat,
  type WhisperSegment,
  type WhisperVerboseResult,
  voiceChat,
  voiceChatStream,
  textToSpeech,
  textToSpeechStream,
  speechToText,
  speechToTextStream,
} from "./client";
